apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lighty-rnc-app-helm.fullname" . }}
  labels:
    {{- include "lighty-rnc-app-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.lighty.replicaCount }}
  selector:
    matchLabels:
      {{- include "lighty-rnc-app-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lighty-rnc-app-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "-c","{{ .Values.lighty.configDirectoryName }}/{{ .Values.lighty.configFilename }}",
                  "-l","{{ .Values.lighty.configDirectoryName }}/{{ .Values.lighty.loggerConfigFilename }}" ]
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.lighty.workdir }}/{{ .Values.lighty.configDirectoryName }}
            - name: secrets-volume
              mountPath: {{ .Values.lighty.workdir }}/{{ .Values.lighty.restconf.keyStoreDirectory }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            {{- if .Values.lighty.jxm.enableJmxRemoting }}
            - name: JAVA_OPTS
              value: "-Dcom.sun.management.jmxremote
                      -Dcom.sun.management.jmxremote.authenticate=false
                      -Dcom.sun.management.jmxremote.ssl=false
                      -Dcom.sun.management.jmxremote.local.only=false
                      -Dcom.sun.management.jmxremote.port={{ .Values.lighty.jxm.jxmPort }}
                      -Dcom.sun.management.jmxremote.rmi.port={{ .Values.lighty.jxm.jxmPort }}
                      -Djava.rmi.server.hostname=127.0.0.1"
            {{- end }}
          ports:
            # akka remoting
            - name: remoting
              containerPort: {{ .Values.lighty.akka.remotingPort }}
              protocol: TCP
            # When
            # akka.management.cluster.bootstrap.contact-point-discovery.port-name
            # is defined, it must correspond to this name:
            - name: management
              containerPort: {{ .Values.lighty.akka.managementPort }}
              protocol: TCP
            # restconf port
            - name: restconf
              containerPort: {{ .Values.lighty.restconf.restconfPort }}
              protocol: TCP
              {{- if .Values.lighty.jxm.enableJmxRemoting }}
              # JXM port on which JXM server is listening
            - name: jxm
              containerPort: {{ .Values.lighty.jxm.jxmPort }}
              protocol: TCP
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "lighty-rnc-app-helm.fullname" . }}
        - name: secrets-volume
          secret:
            secretName: {{ include "lighty-rnc-app-helm.fullname" . }}
            items:
              - key: keystore.jks
                path: {{ .Values.lighty.restconf.keyStoreFileName }}
